import type {
  Account,
  Category,
  Transaction,
  BudgetTemplate,
  MonthlyBudgetOverride,
  DebtRecord,
} from "@/types";

// ─── Accounts ─────────────────────────────────────────────────────────────────

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "BCA Tabungan",
    type: "bank",
    balance: 8_500_000,
    color: "#2563EB",
    icon: "landmark",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-2",
    name: "Kas Tunai",
    type: "cash",
    balance: 750_000,
    color: "#16A34A",
    icon: "banknote",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-3",
    name: "GoPay",
    type: "ewallet",
    balance: 310_000,
    color: "#15803D",
    icon: "wallet",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-4",
    name: "OVO",
    type: "ewallet",
    balance: 125_000,
    color: "#7C3AED",
    icon: "smartphone",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

// ─── Categories ───────────────────────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  // Income
  {
    id: "cat-sal",
    name: "Gaji",
    type: "income",
    icon: "briefcase",
    color: "#16A34A",
    isDefault: true,
  },
  {
    id: "cat-fre",
    name: "Freelance",
    type: "income",
    icon: "laptop",
    color: "#0891B2",
    isDefault: true,
  },
  {
    id: "cat-inv-in",
    name: "Investasi",
    type: "income",
    icon: "trending-up",
    color: "#D97706",
    isDefault: true,
  },
  {
    id: "cat-gift-in",
    name: "Hadiah",
    type: "income",
    icon: "gift",
    color: "#DB2777",
    isDefault: true,
  },

  // Expense
  {
    id: "cat-food",
    name: "Makan & Minum",
    type: "expense",
    icon: "utensils",
    color: "#EA580C",
    isDefault: true,
  },
  {
    id: "cat-transport",
    name: "Transportasi",
    type: "expense",
    icon: "car",
    color: "#2563EB",
    isDefault: true,
  },
  {
    id: "cat-shop",
    name: "Belanja",
    type: "expense",
    icon: "shopping-bag",
    color: "#7C3AED",
    isDefault: true,
  },
  {
    id: "cat-bills",
    name: "Tagihan",
    type: "expense",
    icon: "file-text",
    color: "#DC2626",
    isDefault: true,
  },
  {
    id: "cat-health",
    name: "Kesehatan",
    type: "expense",
    icon: "heart-pulse",
    color: "#DB2777",
    isDefault: true,
  },
  {
    id: "cat-entertain",
    name: "Hiburan",
    type: "expense",
    icon: "tv",
    color: "#9333EA",
    isDefault: true,
  },
  {
    id: "cat-edu",
    name: "Pendidikan",
    type: "expense",
    icon: "book-open",
    color: "#0284C7",
    isDefault: true,
  },
  {
    id: "cat-sub",
    name: "Langganan",
    type: "expense",
    icon: "repeat",
    color: "#6D28D9",
    isDefault: true,
  },
  {
    id: "cat-other-exp",
    name: "Lainnya",
    type: "expense",
    icon: "circle-ellipsis",
    color: "#6B7280",
    isDefault: true,
  },

  // Transfer
  {
    id: "cat-transfer",
    name: "Transfer",
    type: "transfer",
    icon: "arrow-left-right",
    color: "#0891B2",
    isDefault: true,
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────

const now = new Date("2026-03-23");
const thisMonth = "2026-03";
const lastMonth = "2026-02";

export const MOCK_TRANSACTIONS: Transaction[] = [
  // --- March 2026 ---
  {
    id: "txn-001",
    type: "income",
    amount: 12_000_000,
    date: `${thisMonth}-01`,
    categoryId: "cat-sal",
    accountId: "acc-1",
    note: "Gaji bulan Maret",
    createdAt: `${thisMonth}-01T09:00:00Z`,
    updatedAt: `${thisMonth}-01T09:00:00Z`,
  },
  {
    id: "txn-002",
    type: "income",
    amount: 2_500_000,
    date: `${thisMonth}-05`,
    categoryId: "cat-fre",
    accountId: "acc-1",
    note: "Proyek website klien",
    createdAt: `${thisMonth}-05T11:00:00Z`,
    updatedAt: `${thisMonth}-05T11:00:00Z`,
  },
  {
    id: "txn-003",
    type: "expense",
    amount: 350_000,
    date: `${thisMonth}-03`,
    categoryId: "cat-food",
    accountId: "acc-2",
    note: "Belanja bulanan di Indomaret",
    createdAt: `${thisMonth}-03T13:00:00Z`,
    updatedAt: `${thisMonth}-03T13:00:00Z`,
  },
  {
    id: "txn-004",
    type: "expense",
    amount: 250_000,
    date: `${thisMonth}-07`,
    categoryId: "cat-transport",
    accountId: "acc-3",
    note: "Grab bulan Maret",
    createdAt: `${thisMonth}-07T08:00:00Z`,
    updatedAt: `${thisMonth}-07T08:00:00Z`,
  },
  {
    id: "txn-005",
    type: "expense",
    amount: 500_000,
    date: `${thisMonth}-10`,
    categoryId: "cat-bills",
    accountId: "acc-1",
    note: "Listrik & Wi-Fi",
    createdAt: `${thisMonth}-10T10:00:00Z`,
    updatedAt: `${thisMonth}-10T10:00:00Z`,
  },
  {
    id: "txn-006",
    type: "expense",
    amount: 129_000,
    date: `${thisMonth}-12`,
    categoryId: "cat-sub",
    accountId: "acc-1",
    note: "Spotify Premium",
    createdAt: `${thisMonth}-12T00:00:00Z`,
    updatedAt: `${thisMonth}-12T00:00:00Z`,
  },
  {
    id: "txn-007",
    type: "expense",
    amount: 54_000,
    date: `${thisMonth}-12`,
    categoryId: "cat-sub",
    accountId: "acc-1",
    note: "Netflix",
    createdAt: `${thisMonth}-12T00:05:00Z`,
    updatedAt: `${thisMonth}-12T00:05:00Z`,
  },
  {
    id: "txn-008",
    type: "expense",
    amount: 800_000,
    date: `${thisMonth}-15`,
    categoryId: "cat-shop",
    accountId: "acc-1",
    note: "Baju kerja baru",
    createdAt: `${thisMonth}-15T14:00:00Z`,
    updatedAt: `${thisMonth}-15T14:00:00Z`,
  },
  {
    id: "txn-009",
    type: "transfer",
    amount: 500_000,
    date: `${thisMonth}-16`,
    categoryId: "cat-transfer",
    accountId: "acc-1",
    toAccountId: "acc-2",
    note: "Tarik tunai ATM",
    createdAt: `${thisMonth}-16T10:00:00Z`,
    updatedAt: `${thisMonth}-16T10:00:00Z`,
  },
  {
    id: "txn-010",
    type: "expense",
    amount: 200_000,
    date: `${thisMonth}-18`,
    categoryId: "cat-food",
    accountId: "acc-3",
    note: "Makan siang kantor",
    createdAt: `${thisMonth}-18T12:30:00Z`,
    updatedAt: `${thisMonth}-18T12:30:00Z`,
  },
  {
    id: "txn-011",
    type: "expense",
    amount: 1_500_000,
    date: `${thisMonth}-20`,
    categoryId: "cat-health",
    accountId: "acc-1",
    note: "Dokter & obat",
    createdAt: `${thisMonth}-20T09:00:00Z`,
    updatedAt: `${thisMonth}-20T09:00:00Z`,
  },
  {
    id: "txn-012",
    type: "expense",
    amount: 350_000,
    date: `${thisMonth}-22`,
    categoryId: "cat-entertain",
    accountId: "acc-3",
    note: "Bioskop & dinner",
    createdAt: `${thisMonth}-22T19:00:00Z`,
    updatedAt: `${thisMonth}-22T19:00:00Z`,
  },

  // --- February 2026 ---
  {
    id: "txn-013",
    type: "income",
    amount: 12_000_000,
    date: `${lastMonth}-01`,
    categoryId: "cat-sal",
    accountId: "acc-1",
    note: "Gaji bulan Februari",
    createdAt: `${lastMonth}-01T09:00:00Z`,
    updatedAt: `${lastMonth}-01T09:00:00Z`,
  },
  {
    id: "txn-014",
    type: "income",
    amount: 1_000_000,
    date: `${lastMonth}-14`,
    categoryId: "cat-gift-in",
    accountId: "acc-1",
    note: "THR Valentine gift",
    createdAt: `${lastMonth}-14T10:00:00Z`,
    updatedAt: `${lastMonth}-14T10:00:00Z`,
  },
  {
    id: "txn-015",
    type: "expense",
    amount: 450_000,
    date: `${lastMonth}-02`,
    categoryId: "cat-food",
    accountId: "acc-2",
    note: "Belanja mingguan",
    createdAt: `${lastMonth}-02T11:00:00Z`,
    updatedAt: `${lastMonth}-02T11:00:00Z`,
  },
  {
    id: "txn-016",
    type: "expense",
    amount: 300_000,
    date: `${lastMonth}-05`,
    categoryId: "cat-transport",
    accountId: "acc-3",
    note: "Transportasi Februari",
    createdAt: `${lastMonth}-05T08:00:00Z`,
    updatedAt: `${lastMonth}-05T08:00:00Z`,
  },
  {
    id: "txn-017",
    type: "expense",
    amount: 500_000,
    date: `${lastMonth}-10`,
    categoryId: "cat-bills",
    accountId: "acc-1",
    note: "Tagihan listrik",
    createdAt: `${lastMonth}-10T10:00:00Z`,
    updatedAt: `${lastMonth}-10T10:00:00Z`,
  },
  {
    id: "txn-018",
    type: "expense",
    amount: 650_000,
    date: `${lastMonth}-14`,
    categoryId: "cat-entertain",
    accountId: "acc-1",
    note: "Valentine dinner",
    createdAt: `${lastMonth}-14T19:00:00Z`,
    updatedAt: `${lastMonth}-14T19:00:00Z`,
  },
  {
    id: "txn-019",
    type: "expense",
    amount: 1_200_000,
    date: `${lastMonth}-20`,
    categoryId: "cat-shop",
    accountId: "acc-1",
    note: "Sepatu baru",
    createdAt: `${lastMonth}-20T13:00:00Z`,
    updatedAt: `${lastMonth}-20T13:00:00Z`,
  },
  {
    id: "txn-020",
    type: "expense",
    amount: 400_000,
    date: `${lastMonth}-25`,
    categoryId: "cat-edu",
    accountId: "acc-1",
    note: "Buku programming",
    createdAt: `${lastMonth}-25T10:00:00Z`,
    updatedAt: `${lastMonth}-25T10:00:00Z`,
  },
];

// ─── Budget Template ──────────────────────────────────────────────────────────

export const MOCK_BUDGET_TEMPLATE: BudgetTemplate = {
  id: "bt-1",
  items: [
    { categoryId: "cat-food", amount: 1_500_000 },
    { categoryId: "cat-transport", amount: 500_000 },
    { categoryId: "cat-bills", amount: 600_000 },
    { categoryId: "cat-shop", amount: 600_000 },
    { categoryId: "cat-health", amount: 500_000 },
    { categoryId: "cat-entertain", amount: 400_000 },
    { categoryId: "cat-sub", amount: 300_000 },
    { categoryId: "cat-edu", amount: 300_000 },
    { categoryId: "cat-other-exp", amount: 200_000 },
  ],
  updatedAt: "2026-01-01T00:00:00Z",
};

// ─── Monthly Budget Overrides ─────────────────────────────────────────────────

export const MOCK_BUDGET_OVERRIDES: MonthlyBudgetOverride[] = [
  {
    id: "mbo-1",
    monthKey: "2026-03",
    // March: increased health budget due to appointment
    items: [
      { categoryId: "cat-health", amount: 2_000_000 },
      { categoryId: "cat-food", amount: 1_800_000 },
    ],
    updatedAt: "2026-03-01T00:00:00Z",
  },
];

// ─── Debt / Credit Records ────────────────────────────────────────────────────

export const MOCK_DEBTS: DebtRecord[] = [
  {
    id: "debt-1",
    direction: "lent",
    personName: "Budi Santoso",
    originalAmount: 2_000_000,
    settledAmount: 500_000,
    status: "partially_settled",
    description: "Pinjaman untuk keperluan mendadak",
    dueDate: "2026-04-30",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "debt-2",
    direction: "lent",
    personName: "Siti Rahayu",
    originalAmount: 500_000,
    settledAmount: 500_000,
    status: "settled",
    description: "Patungan makan siang",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "debt-3",
    direction: "borrowed",
    personName: "Pak Andi",
    originalAmount: 3_000_000,
    settledAmount: 0,
    status: "active",
    description: "Pinjaman untuk bayar kost",
    dueDate: "2026-05-01",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "debt-4",
    direction: "lent",
    personName: "Agus Widodo",
    originalAmount: 1_000_000,
    settledAmount: 0,
    status: "active",
    description: "Modal usaha kecil",
    dueDate: "2026-06-01",
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
];

// Export a validation-ready object (used for API contract mirroring)
export const MOCK_DATA = {
  accounts: MOCK_ACCOUNTS,
  categories: MOCK_CATEGORIES,
  transactions: MOCK_TRANSACTIONS,
  budgetTemplate: MOCK_BUDGET_TEMPLATE,
  budgetOverrides: MOCK_BUDGET_OVERRIDES,
  debts: MOCK_DEBTS,
} as const;

export type MockData = typeof MOCK_DATA;

// Unused variable suppressor for the `now` variable used in context
void now;
